name: Mirror repo
on: [push]

jobs:
  mirror:
    if: github.repository == 'mozilla/release-notes'
    runs-on: ubuntu-latest
    steps:
       - name: mirror in gitlab
         uses: actions/checkout@v3
         with:
          fetch-depth: 0
       - uses: yesolutions/mirror-action@71cd8f5b5c9c4a461f477ecccace98850cb04bc1
         with:
            REMOTE: 'https://gitlab.com/mozmeao/release-notes.git'
            GIT_USERNAME: ${{ secrets.GITLAB_USERNAME }}
            GIT_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
